FROM amazoncorretto:21.0.5-al2023-headless

ENV SCALA_VERSION 3.5.2
ENV SBT_VERSION 1.5.5

WORKDIR /knockout

COPY build.sbt /knockout/
COPY project /knockout/project/

RUN sbt update

COPY . /knockout

RUN apt-get update
RUN apt-get install -y libgtk-3-0 libglib2.0-0 libxext6 libxrender1 libxtst6 libx11-6 xvfb libxi6

RUN sbt compile

CMD sbt run

ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $ip


 docker run -it --rm \
    -e DISPLAY=host.docker.internal:0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    knockout:v1